### ISSUE TITLE
Demande accès - Resp Com BdE

### ISSUE THREAD

**Issue by AdrienDesproges** [BdEINSALyon/logos-bde#4]
Hello ! 
Déso si je met pas ma demande au bon endroit, je maitrise pas encore GitHub :/
Je suis le nouveau resp com du bde et il me faudrait les accès pour modifier facilement le site **logos.bde-insa-lyon.fr**. 
Normalement si j'ai bien compris je peux le faire directement depuis GitHub :)
Merci ! 
Adrien DESPROGES

**Comment by Mogier** [comment]
Salut Michel,

Félicitations j'imagine ?
A mon avis demande plutôt directement aux Orga IF si cette espèce en voie
de disparition existe toujours.

Si jamais tu peux leur demander de faire du tri dans les membres du Github
au passage ça ferait sans doute pas de mal (VP en 2014/2015 je sais pas ce
que je fais encore là).

Bon chance pour ton mandat.
Mogier

Le jeu. 8 juil. 2021 à 20:51, AdrienDesproges ***@***.***> a
écrit :

**Comment by JeanRibes** [comment]
bravo pour ta proactivité, mais malheureusement on a migré sur Gitlab, il ne reste plus que les vieux ici
l'équipe OrgaIF n'existe plus car elle a été remplacée par le SIA
va voir notre site https://sia.asso-insa-lyon.fr/ pour le contact (go Discord), et mentionne ton nom d'utilisateur Gitlab

le site https://logos.bde-insa-lyon.fr/ n'est même plus hébergé sur Github Pages
